### ISSUE TITLE
无法顺利退出

### ISSUE THREAD

**Issue by Cassian824** [FurryR/lightpad#2]
在Windows11+Windows终端+wsl(ubuntu22.04LTS gcc 11.3.0）环境下,lightpad输入 “：q”无法顺利退出
例如，当输入：
./lightpad
：q
后，虽然回到了终端界面，但是本行终端提示符的第一个字母跑到了前一行。按Enter在新一行继续输入命令会发现命令不显示（而非与背景颜色一致）。

**Comment by FurryR** [comment]
截图谢谢

**Comment by FurryR** [comment]
抱歉，这个项目只适用于 zsh，正在进行处理。

**Comment by FurryR** [comment]
是 bash 的问题，不予修复。

**Comment by FurryR** [comment]
在新的版本中已解决这个问题，感谢汇报。
