### ISSUE TITLE
在特定情况下文件内容显示异常

### ISSUE THREAD

**Issue by Cassian824** [FurryR/lightpad#3]
以打开本项目main.cpp为例，
./lightpad main.cpp
此时如果一直长按右方向键会导致字符消失错位。
环境：
WSL2
Ubuntu22.04LTS
Bash
问题图如下：
![image](https://user-images.githubusercontent.com/106961263/205474087-711a9f2c-eee0-4706-a93f-70a28129aa10.png)

**Comment by FurryR** [comment]
Lightpad不支持中文显示。main.cpp含有中文，会导致错误的渲染。您可以提交一份支持中文的 Screen API 来解决这个问题。
