### ISSUE TITLE
MSYS2退出程序后控制台输入文本无回显

### ISSUE THREAD

**Issue by K926v3C** [FurryR/lightpad#6]
编译器：GCC 11.3.0-2
GNU Make版本：4.4-1

**Comment by FurryR** [comment]
请提供问题复现截图。

**Comment by FurryR** [comment]
Is it a duplicate of #2 ?

**Comment by K926v3C** [comment]
![MSYS2退出程序后运行命令](https://user-images.githubusercontent.com/110602013/205825216-de0bcfbb-710e-4cb4-99ea-49d2326bac08.png)

注：图中马赛克的部分为用户名。

**Comment by FurryR** [comment]
可以顺便附带一张运行时的截图吗？非常感谢。

**Comment by K926v3C** [comment]
> Is it a duplicate of #2 ?

我本来打算补充更多信息，但是你提前关闭了Issue。

**Comment by K926v3C** [comment]
![image](https://user-images.githubusercontent.com/110602013/205825709-9e55bc3e-4a83-4733-88d1-d3d30e01dd4f.png)

**Comment by FurryR** [comment]
> > Is it a duplicate of #2 ?
> 
> 我本来打算补充更多信息，但是你提前关闭了Issue。

非常抱歉。我们正在复现环境，请稍等。
您有任何解决的思路吗？

**Comment by K926v3C** [comment]
> > > Is it a duplicate of #2 ?
> > 
> > 
> > 我本来打算补充更多信息，但是你提前关闭了Issue。
> 
> 非常抱歉。我们正在复现环境，请稍等。 您有任何解决的思路吗？

暂时没有，我只是在试用程序的时候发现的问题，顺手提的Issue。

**Comment by FurryR** [comment]
好的。我们现在怀疑程序在退出时未进行清理。您使用什么方法退出程序呢？您有没有确认过atexit是否被触发？

**Comment by K926v3C** [comment]
> 好的。我们现在怀疑程序在退出时未进行清理。您使用什么方法退出程序呢？您有没有确认过atexit是否被触发？

我刚才查看了源代码，也有同样的猜想。

我是通过键盘输入`:q` + `[Enter]`退出程序的。

atexit暂时没有检查。

**Comment by FurryR** [comment]
谢谢您的协作。
我还有一个问题。
msys2 编译的程序可以在 Windows 上直接运行么？我希望制作 Lightpad 的 Windows 版。

**Comment by K926v3C** [comment]
> 谢谢您的协作。 我还有一个问题。 msys2 编译的程序可以在 Windows 上直接运行么？我希望制作 Lightpad 的 Windows 版。

可以，MSYS2提供了交叉编译（Cross Compile）所需的工具链。

具体信息可以通过[MSYS2官网](https://www.msys2.org/)和网络上的其他文章了解。

**Comment by FurryR** [comment]
太好了！这意味着我可以移除对 Win32 的支持。

**Comment by FurryR** [comment]
我们在 msys2 上成功编译了程序，但是没有发现问题。
这很可能是因为您自行对旧版本的 usleep 进行了修改导致的。
这是我们对使用画面的截图。
您可 `git pull` 新版后再试试。
介于不能完全确定，我将不会将这个问题存档。若问题仍存在，请务必在本issue提出问题（我会持续关注）。
![スクリーンショット 2022-12-08 081332](https://user-images.githubusercontent.com/55276797/206324995-c5423e7a-02c0-45b6-b1f7-4c0f1b7f4788.png)
