### ISSUE TITLE
编译时错误

### ISSUE THREAD

**Issue by ColorAWA** [FurryR/lightpad#8]
# make build
[CXX] main.cpp -> lightpad
In file included from main.cpp:6:
./command.h:7:10: fatal error: ./awacorn/awacorn.h: 没有那个文件或目录
    7 | #include "./awacorn/awacorn.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:7：build] 错误 1

**Comment by Cassian824** [comment]
awacorn文件夹似乎是作者另一个项目的“引用”，所以你需要进一步操作，获取awacorn仓库，来编译项目。你也可以手动从作者的awacorn仓库下载源码

**Comment by ColorAWA** [comment]
> 
谢，解决了
